spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: asd
  jpa:
    hibernate:
      ddl-auto: update
Server:
  port: 8085