spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://104.248.157.125:5437/customer_db
    username: postgres
    password: asd
  jpa:
    hibernate:
      ddl-auto: update
Server:
  port: 8085